version: '3'
services:
  sivel2_backend:
    container_name: sivel2_backend
    build: ./sivel2
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./sivel2/:/code/
      - rubygems:/usr/local/bundle
      - ./sivel2_api/:/sivel2_api
    links:
      - sivel2_database
    tty: true
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    command: rails s 
  sivel2_frontend:
    container_name: sivel2_frontend
    build: ./sivel2_frontend
    volumes:
      - ./sivel2_frontend:/code
    ports:
      - "4000:4000"
    links:
      - sivel2_backend
    tty: false
    command: yarn start
  sivel2_database:
    container_name: sivel2_database
    build: ./db
    volumes:
      - ./db/:/code
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    tty: true
volumes:
  rubygems:
